### ISSUE TITLE
translate command output to English

### ISSUE THREAD

**Issue by Sammeeey** [Sammeeey/plzCrawler#3]
### file:
[plzMaker.py](https://github.com/Sammeeey/plzCrawler/blob/main/plzcrawler/plzMaker.py)

### What to do?
- [x] translate print statements to English

**Comment by kiritocode1** [comment]
ill take this one as well 😶🤟🤟🤟

**Comment by Sammeeey** [comment]
Hey, great!
Than we almost have it completely in english 😁

**Comment by kiritocode1** [comment]
**covered Print requests**
**covered docs**
**covered  comments**
#5
